name: Secure Scraper

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      FIREBASE_CFG: ${{ secrets.FIREBASE_CFG }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create config file
      run: |
        mkdir -p config
        echo '${{ secrets.FIREBASE_CFG }}' > config/firebase-cfg.json

    - name: Run scraper
      run: npm start