name: Real Estate Scraper

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --no-audit --prefer-offline

    - name: Create .env file
      run: |
        echo "FIREBASE_CREDENTIALS='${{ secrets.FIREBASE_CREDENTIALS }}'" > .env
        echo "FIREBASE_DB_URL='${{ secrets.FIREBASE_DB_URL }}'" >> .env

    - name: Run Scraper
      run: npm start