name: Image Link Scraper
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: 'tests/package-lock.json'  # Updated path

      - name: Install dependencies
        working-directory: ./tests  # Add working directory
        run: npm ci

      - name: Run scraper
        working-directory: ./tests  # Add working directory
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
        run: node simple-scraper.js