name: Real Estate Scraper

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevent hanging jobs
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4

    - name: Set up Node.js 20
      uses: actions/setup-node@v4  # Updated to v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies securely
      run: |
        # Update npm to latest version
        npm install -g npm@latest
        
        # Install with security audit
        npm install --omit=dev --ignore-scripts --audit
        
        # Fix critical vulnerabilities
        npm audit fix --force || true
        
        # Clean cache
        npm cache clean --force

    - name: Run scraper with enhanced logging
      env:
        FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      run: |
        mkdir -p config
        echo "$SERVICE_ACCOUNT" > config/firebase-cfg.json
        
        # Run with detailed logging
        node --unhandled-rejections=strict scraper.js 2>&1 | tee scraper.log
        
        # Check exit status and log output
        if [ ${PIPESTATUS[0]} -ne 0 ]; then
          echo "::error::Scraper failed with exit code ${PIPESTATUS[0]}"
          cat scraper.log
          exit 1
        fi

    - name: Upload logs for debugging
      if: failure()
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: scraper-logs
        path: |
          scraper.log
          npm-debug.log*