name: Real Estate Scraper

on:
  schedule:
    - cron: '5,35 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevent hanging jobs

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4

    - name: Set up Node.js 20
      uses: actions/setup-node@v4  # Updated to v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies securely
      run: |
        # Update npm to latest version
        npm install -g npm@latest
        
        # Install with security audit
        npm install --omit=dev --ignore-scripts --audit
        
        # Fix critical vulnerabilities
        npm audit fix --force || true
        
        # Clean cache
        npm cache clean --force

    - name: Run scraper
      env:
        FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      run: |
        mkdir -p config
        echo "$SERVICE_ACCOUNT" > config/firebase-cfg.json
        npm start

    - name: Upload logs for debugging
      if: failure()
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: scraper-logs
        path: |
          scraper.log
          npm-debug.log*

  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq (for JSON parsing)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Delete all workflow runs
        env:
          REPO: ${{ github.repository }}
          PAT: ${{ secrets.DELETE_RUN_PAT }}
          WORKFLOW_FILE: scraper.yml
        run: |
          # Fetch the first 100 workflow-run IDs
          RUN_IDS=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $PAT" \
            "https://api.github.com/repos/$REPO/actions/workflows/$WORKFLOW_FILE/runs?per_page=100" \
            | jq -r '.workflow_runs[].id')

          for id in $RUN_IDS; do
            echo "Deleting run #$id..."
            curl -s -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token $PAT" \
              "https://api.github.com/repos/$REPO/actions/runs/$id"
          done